<a href="https://colab.research.google.com/github/viti990/PyTorchCourse/blob/main/pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.2.1+cu121


In [2]:
scalar = torch.tensor(7)

In [3]:
scalar.ndim

0

In [4]:
scalar.item()

7

In [5]:
vector = torch.tensor([1,2])

In [6]:
vector.ndim


1

In [7]:
vector.shape

torch.Size([2])

In [8]:
# MATRIX

MATRIX = torch.tensor([[1,2],
                       [3,4]])
MATRIX

tensor([[1, 2],
        [3, 4]])

In [9]:
MATRIX.ndim

2

In [10]:
MATRIX.shape

torch.Size([2, 2])

In [11]:
# TENSOR
TENSOR = torch.tensor([[[1,2,3],
                       [4,5,6],
                       [7,8,9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [12]:
TENSOR.ndim

3

In [13]:
TENSOR.shape

torch.Size([1, 3, 3])

In [14]:
TENSOR[0][1][2].item()

6

### Random tensors

Why use them?

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

`start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

In [15]:
# create a random tensor of shape(3,4)

random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.0010, 0.7524, 0.2097, 0.2737],
        [0.8201, 0.5295, 0.5093, 0.0214],
        [0.1034, 0.5454, 0.6063, 0.4571]])

In [16]:
random_tensor.ndim

2

In [17]:
#create a random tensor with a similar shape to an image
random_image_sixe_tensor = torch.rand(size = (244,244,3)) #heigh, width colour channel
random_image_sixe_tensor.shape, random_image_sixe_tensor.ndim

(torch.Size([244, 244, 3]), 3)

In [18]:
# create a tensor of all zeroes
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [19]:
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [20]:
# create a tensor of all ones
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [21]:
ones.dtype

torch.float32

###create a range of tensor and tensors-like

In [22]:
#use torch.range() and get deprecated message or use torch.arange()
torch.arange(0,10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
torch.__version__

'2.2.1+cu121'

In [24]:
one_to_ten = torch.arange(start=1, end=11, step= 1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [25]:
# Creating tensors like
ten_zeroes = torch.zeros_like(input=one_to_ten)
ten_zeroes

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

** Note: ** Tensor datatypes is one of the 3 big errors you'll run into with Pytorch & deep learning:

1. Tensors no right datatype
2. Tensors not being the right shape
3. Tensorsnot on the right device

In [26]:
#float 43 tensor
float_32_tensor = torch.tensor([3.0,6.0,9.0],
                               dtype = None, # what datatype is the tensor e.g. float32 or float16
                               device = None, # what device your tensor is on e.g. CPU vs GPU
                               requires_grad = False) # whether or not to track gradients
float_32_tensor

tensor([3., 6., 9.])

In [27]:
float_32_tensor.dtype

torch.float32

In [28]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [29]:
float_32_tensor * float_16_tensor

tensor([ 9., 36., 81.])

In [30]:
in_32_tensor = torch.tensor([3,6,9], dtype = torch.long)

In [31]:
float_32_tensor * in_32_tensor

tensor([ 9., 36., 81.])

### Getting information from tensors

1. Tensors no right datatype -  to do get dataype from a tensor, can use `tensor.dtype`
2. Tensors not being the right shape - to get shape from a tensor, can use `tensor.shape`
3. Tensorsnot on the right device - to get device from  atensor, can use `tensor.device`

In [32]:
# create a tensor
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.1865, 0.2054, 0.3464, 0.3864],
        [0.8212, 0.3248, 0.0540, 0.6810],
        [0.3306, 0.5025, 0.0383, 0.1752]])

In [33]:
# Find out details about some tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.1865, 0.2054, 0.3464, 0.3864],
        [0.8212, 0.3248, 0.0540, 0.6810],
        [0.3306, 0.5025, 0.0383, 0.1752]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


### Manipulating Tensor (tensor operations)

Tensor operations include:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix mulltiplication

In [34]:
# Create a tensor and add 10 to it
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [35]:
# Multiply tensor by 10
tensor * 10

tensor([10, 20, 30])

In [36]:
# subtract 10
tensor - 10

tensor([-9, -8, -7])

In [37]:
# Try out torch in-built functions
torch.mul(tensor,10)

tensor([10, 20, 30])

In [38]:
torch.add(tensor,10)

tensor([11, 12, 13])

### Matrix multiplication

two main ways of performing multiplication in neural networks and deep learning

1. Element-wise multiplication
2. Matrix multiplication (dot product)

There are two main rules that matrix multiplication needs to satisfy
1. The **Inner dimensions** must mtach:
* `(3,2) @ (3,2)` won't work
* `(2,3) @ (3,2)` will work
* `(3,2) @ (2,3)` will work
2. The resulting matrix has the shape of the **outer dimensions**:
* `(2,3) @ (3,2)` -> `(2,2)`
* `(3,2) @ (2,3)` -> `(3,3)`

In [39]:
#Element-wise multiplication
print(tensor, "+", tensor)
print(f"Equals: {tensor*tensor}")

tensor([1, 2, 3]) + tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [40]:
torch.matmul(tensor, tensor)

tensor(14)

In [41]:
# Matrix multiplication by hand
1*1 + 2*2 + 3*3

14

In [42]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: user 2.34 ms, sys: 0 ns, total: 2.34 ms
Wall time: 3.3 ms


In [43]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 1.22 ms, sys: 0 ns, total: 1.22 ms
Wall time: 1.06 ms


tensor(14)

In [44]:
torch.matmul(torch.rand(3,10),torch.rand(10,3)).shape

torch.Size([3, 3])

### One of the most common errors in deep learning shape erros

In [45]:
# Shapes fot amtrix multiplication
tensor_A = torch.tensor([[1,2],
                        [3,4],
                        [5,6]])
tensor_B = torch.tensor([[7,10],
                        [8,11],
                        [9,12]])
torch.mm(tensor_A, tensor_B.T) # torch.mm is the same as torch.matmul  (it's an alias fowriting less code)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

In [46]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

To fix our tensor shape issues, we can manupulate the shape of one of our tensors using a **transpose**

A **transpose switched the axes or dimensions of a given tensor.

In [47]:
tensor_B.T, tensor_B

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]))

In [48]:
# the matrix multiplication operation works when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}")
print(f"New shapes: tensor_A: {tensor_A.shape} (same shape as above), tensor_B.T = {tensor_B.T.shape}")
print(f"Multiplying: {tensor_A.shape} @ {tensor_B.T.shape} <- inner dimensions must match")
print("Output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f"\nOutput shape: {output.shape}")

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])
New shapes: tensor_A: torch.Size([3, 2]) (same shape as above), tensor_B.T = torch.Size([2, 3])
Multiplying: torch.Size([3, 2]) @ torch.Size([2, 3]) <- inner dimensions must match
Output:

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

Output shape: torch.Size([3, 3])


In [49]:
tensor_A.T @ tensor_B

tensor([[ 76, 103],
        [100, 136]])

## Finding the min, max mean, sum etc (tensor aggregation)

In [50]:
# Create a tensor
x = torch.arange(0,100,10)
x, x.dtype

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), torch.int64)

In [51]:
#find the min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [52]:
# Find the max
torch.max(x), x.max()

(tensor(90), tensor(90))

In [53]:
# Find the mean - note: the torch.mean() function requires a tensor of float32 datatype to work
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [54]:
# Find the sum
torch.sum(x), x.sum()

(tensor(450), tensor(450))

In [55]:
x.argmin()

tensor(0)

In [56]:
x[0]

tensor(0)

In [57]:
x.argmax()

tensor(9)

In [58]:
x[9]

tensor(90)

## Reshaping, stacking, squeezing and unsqueezing tensors

* Reshaping - reshapes an input tensor to a defined shape
* View - Return a view of an input tensor of a certain shape but keep the same memory as the original tensor
* Stacking - combine multiple on top of each other (vstack) or side by side (hstack)
* Squeeze - remove all `1` dimensions from a tensor
* Unsqueeze - add a `1` dimension to a target tensor
* Permute - Return a view of the input with dimensions permuted (swapped) in a certain way

In [59]:
# Let's create a tensor
x = torch.arange(1.,10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [60]:
# add an extra dimension
x_reshaped = x.reshape(1,9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [61]:
# Change the view (shares the memory with initial tensor)
z = x.view(1,9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [62]:
# Changing z changes x (Because a view of a tensor shares the smae memory as the original tensor)
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [63]:
# Stack tensors on top of each other
x_stacked = torch.stack([x,x,x,x], dim = 1)
x_stacked

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [64]:
# torch.squeeze() - removes all single dimensions from a target tensor
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# Remove extra dimension from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous shape: torch.Size([1, 9])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape: torch.Size([9])


In [65]:
# torch.unqueeze() - adds a single dimension to a target tensor at aa specific dim (dimension)
print(f"Previous target: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

# Add extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=1)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New Shape: {x_unsqueezed.shape}")

Previous target: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])

New tensor: tensor([[5.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])
New Shape: torch.Size([9, 1])


In [66]:
x_reshaped.squeeze()

tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])

In [67]:
x_reshaped.squeeze().shape

torch.Size([9])

In [68]:
# torch.permute() - rearranges the dimensions of a target tensor in a specified order
x_original = torch.rand(size=(224,224,3)) # [height, width, colour_channels]
# Permute the original tensor to rearrange the axis (or dim) order
x_permuted = x_original.permute(2,0,1) # shifts axis 0 -> 1, 1->2, 2->0

print(f"Previous shape: {x_original.shape}")
print(f"New shape : {x_permuted.shape}") # [colour_channels, height, width]

Previous shape: torch.Size([224, 224, 3])
New shape : torch.Size([3, 224, 224])


In [69]:
x_original[0,0,0] = 728218
x_original[0,0,0], x_permuted[0,0,0]

(tensor(728218.), tensor(728218.))

## Indexing (selecting data from tensors)

Indexing with PyTorch is similar to indexing with NumPy

In [70]:
# Create a tensor
x = torch.arange(1,10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [71]:
# Let's index on our new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [72]:
# Let's index on the middle bracket (dim = 1)
x[0][0], x[0,0]

(tensor([1, 2, 3]), tensor([1, 2, 3]))

In [73]:
# Let's index on the most inner bracket (last dimension)
x[0,2,2]

tensor(9)

In [74]:
# You can also use ":" to select "all" of a target dimension
x[:,0]

tensor([[1, 2, 3]])

In [75]:
# Get all values of 0th and 1st dimensions but only index 1 of 2nd dimension
x[:,:,1]

tensor([[2, 5, 8]])

In [76]:
# Get all values of the 0 dimension but only the 1 index value of the 1st and 2nd dimension
x[:,1,1]

tensor([5])

In [77]:
# Get index 0 of the 0th and 1st dimension and all the values of the 2nd dimension
x[0,0,:]

tensor([1, 2, 3])

In [78]:
# Index on x to return 9
print(x[0][2][2])

#Index on x to return 3,6,9
print(x[:,:,2])

tensor(9)
tensor([[3, 6, 9]])


## PyTorch tensor & NumPy

NumPy is a popular scientific Python numerical computing library

And because of this PyToorch has functionality to interact with it.

* Data in NumPy, want in PyTorch tensor -> `torch.from_numpy(ndarray)`

* PyTorch tensor -> NumPy -> `torch.Tensor.numpy()`


In [79]:
#NumPy array to tensor

array = np.arange(1. , 8.)
tensor = torch.from_numpy(array).type(torch.float32) #warning when converting from NumPy -> PyTorch, Pytorch reflects numpy's default datatype of float64 unles specified otherwise
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [80]:
array.dtype

dtype('float64')

In [81]:
torch.arange(1.,8.).dtype

torch.float32

In [82]:
# Change the value of array, what will this do to `tensor`?

array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [83]:
# Tensor to NumPy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [84]:
numpy_tensor.dtype

dtype('float32')

In [85]:
# Change the tensor, what happens to `numpy_tensor`?
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducibility(trying to take random out of random)
In short how a neural network learns:

`start with random numbers -> tensor operations -> update random numbers to try and
 make them better representation of the data -> agains -> again -> again...`

 To reuce the randomness in neural networks and PyTorch comes the concept of ** random seed**

 Essentially what the random seed does is "flavour" the randomness.

In [86]:
torch.rand(3,3)

tensor([[0.5218, 0.6896, 0.1024],
        [0.5015, 0.8777, 0.8431],
        [0.2964, 0.0839, 0.6272]])

In [87]:
# Create two random tensors

random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.4141, 0.8993, 0.8051, 0.0073],
        [0.2778, 0.9626, 0.6473, 0.6906],
        [0.5689, 0.6081, 0.2300, 0.5217]])
tensor([[0.0072, 0.1958, 0.3855, 0.3748],
        [0.2919, 0.1908, 0.6423, 0.4837],
        [0.8330, 0.0222, 0.9875, 0.0534]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [88]:
 # let's make some random but reproducible tensors

RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)

random_tensor_C = torch.rand(3,4)
torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3,4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## Running tensors and PyTorch objects on gpus ( and making faster computations)

GPUs = faster computation on number, tjanks tp VUDA + NVIDIA hardware + PyTorch working behind the scenes to make everything good

### 1. Getting a GPU

1. Easiest - Use googl colab for a free gpu (options to upgrade as well)
2. Use your own GPU - takes a little bit of setup and requires the investment of purchasing a GPU, there's lots of options...
3. Use of cloud computing - GCP, AWS, Azure, these services allow you to rent computers on the cloud and access them

for 2, 3 PyTorch + GPU drivers (CUDA) takes a little bit of setting up, to do this, refer to PyTorch documentation

In [89]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


### 2. Check for GPU access with PyTorch

In [90]:
# Check for GPU access with PyTorch
torch.cuda.is_available()

False

For PyTorch since it's capable of running compute on the GPU or CPU, i's besto practice to setup device agnostic code
e.g. run o GPU if available, else default to CPU

In [91]:
# Setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cpu'

In [92]:
# Count the number of devices
torch.cuda.device_count()

0

## 3. Putting tensors (and models) on the GPU
The reason we want our tensors/models on the PGU is because using a GPU results in faster computations.

In [93]:
# Create a tensor (default on CPU)
tensor = torch.tensor([1,2,3])

# Tensor not on GPU
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [94]:
# MOve tensor to FPu (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3])

### 4. Moving tensor back to the CPU

In [95]:
# To fix the gpu tensor with NumPy issem we can first set it to the CPU
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

In [96]:
# If tensor is on GPU, can't transform it to NumPy
tensor_on_gpu

tensor([1, 2, 3])