# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [ ]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [2]:
# Import torch
import torch

# Create random tensor
a = torch.rand(7,7)

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [3]:
# Create another random tensor
b = torch.rand(1,7)
# Perform matrix multiplication
torch.matmul(a,b.T)

tensor([[1.2089],
        [1.2118],
        [1.1222],
        [1.4338],
        [1.0942],
        [1.9850],
        [1.3559]])

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [4]:
# Set manual seed
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
# Create two random tensors
a = torch.rand(1,2)
torch.manual_seed(RANDOM_SEED)
b = torch.rand(2,1)

# Matrix multiply tensors
a @ b

tensor([[1.6156]])

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [5]:
# Set random seed on the GPU
torch.cuda.manual_seed(1234)



### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [12]:
# Set random seed
torch.cuda.manual_seed(1234)

# Check for access to GPU
print(torch.cuda.is_available())
# Create two random tensors on GPU
a = torch.rand(3,4, device='cuda')
b = torch.rand(4,5, device='cuda')
a, b

True


(tensor([[0.1272, 0.8167, 0.5440, 0.6601],
         [0.2721, 0.9737, 0.3903, 0.3394],
         [0.5451, 0.7312, 0.3864, 0.5959]], device='cuda:0'),
 tensor([[0.6208, 0.0276, 0.3255, 0.1114, 0.6812],
         [0.3608, 0.1715, 0.1965, 0.8400, 0.0438],
         [0.3011, 0.0285, 0.1628, 0.6302, 0.0447],
         [0.0927, 0.5736, 0.1185, 0.8971, 0.0516]], device='cuda:0'))

In [6]:
!nvidia-smi

Fri Apr 12 21:26:31 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   35C    P8               9W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--


### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [14]:
# Perform matmul on tensor_A and tensor_B
c = torch.matmul(a,b)

### 8. Find the maximum and minimum values of the output of 7.

In [16]:
# Find max
print(c.max())
# Find min
print(c.min())

tensor(1.6352, device='cuda:0')
tensor(0.1807, device='cuda:0')


### 9. Find the maximum and minimum index values of the output of 7.

In [17]:
# Find arg max
print(c.argmax())

# Find arg min
print(c.argmin())

tensor(3, device='cuda:0')
tensor(4, device='cuda:0')



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [19]:
# Set seed
torch.cuda.manual_seed(7)

# Create random tensor
a = torch.rand(1,1,1,10)

# Remove single dimensions
b = a.squeeze()

# Print out tensors and their shapes
print(a, a.shape, end = "\n")
print(b, b.shape)

tensor([[[[0.6947, 0.0897, 0.8712, 0.1330, 0.4137, 0.6044, 0.7581, 0.9037,
           0.9555, 0.1035]]]]) torch.Size([1, 1, 1, 10])
tensor([0.6947, 0.0897, 0.8712, 0.1330, 0.4137, 0.6044, 0.7581, 0.9037, 0.9555,
        0.1035]) torch.Size([10])
